### ISSUE TITLE
Basic authentication does not work anymore

### ISSUE THREAD

**Issue by JonasJes** [mycortex/python-verisure-climate#3]
I just installed this to my HA, and really hoped it would add the heatpump for my automations
Unfortunately, the authentication method does not look like it is working anymore

```
ERROR (MainThread) [homeassistant.components.climate] Error while setting up verisureclimate platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/verisureclimate/climate.py", line 92, in setup_platform
    session.login()
  File "/config/custom_components/verisureclimate/verisure/session.py", line 93, in login
    self._create_cookie()
  File "/config/custom_components/verisureclimate/verisure/session.py", line 123, in _create_cookie
    raise ResponseError(response.status_code, response.text)
custom_components.verisureclimate.verisure.session.ResponseError: Invalid response, status code: 401 - Data: {"errorGroup":"UNAUTHORIZED","errorCode":"AUT_00048","errorMessage":"Not allowed to use basic authentication with a CPE user on this resource"}
```

**Comment by troppavegen84** [comment]
I have the same problem. Is there going to be a fix to solve this issue?
